project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_KEY

preserve_hierarchy: true

files:
  # Theme translations
  - source: /i18n/en/code.json
    translation: /i18n/%two_letters_code%/code.json

  - source: /i18n/en/docusaurus-theme-classic/navbar.json
    translation: /i18n/%two_letters_code%/docusaurus-theme-classic/navbar.json

  - source: /i18n/en/docusaurus-theme-classic/footer.json
    translation: /i18n/%two_letters_code%/docusaurus-theme-classic/footer.json

  # Plugin translations
  - source: /i18n/en/docusaurus-plugin-content-docs/current.json
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current.json

  - source: /i18n/en/docusaurus-plugin-content-blog/options.json
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/options.json

  # Document content translations (excluding media-insights language-specific pages)
  - source: /i18n/en/docusaurus-plugin-content-docs/current/**/*.md
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    ignore:
      - /i18n/en/docusaurus-plugin-content-docs/current/media-insights/spanish.md
      - /i18n/en/docusaurus-plugin-content-docs/current/media-insights/italian.md
      - /i18n/en/docusaurus-plugin-content-docs/current/media-insights/hungarian.md
      - /i18n/en/docusaurus-plugin-content-docs/current/media-insights/german.md
      - /i18n/en/docusaurus-plugin-content-docs/current/media-insights/french.md
      - /i18n/en/docusaurus-plugin-content-docs/current/media-insights/english.md
      - /i18n/en/docusaurus-plugin-content-docs/current/media-insights/dutch.md
      - /i18n/en/docusaurus-plugin-content-docs/current/media-insights/czech-slovak.md

