name: Crowdin Translation Sync

on:
  # Run when main branch is updated
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'i18n/en/**'

  # Allow manual trigger
  workflow_dispatch:

  # Run on schedule to pull new translations
  schedule:
    # Run every day at 6 AM UTC to check for new translations
    - cron: '0 6 * * *'

jobs:
  crowdin-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Need full history for git operations
          fetch-depth: 0
          # Use a token that can push to the repository
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate translation templates
        run: npm run write-translations

      - name: Update source docs for translation
        run: |
          # Sync any new/updated docs to translation source
          cp -r docs/* i18n/en/docusaurus-plugin-content-docs/current/
          # Remove media-insights language files (shouldn't be translated)
          rm -f i18n/en/docusaurus-plugin-content-docs/current/media-insights/spanish.md
          rm -f i18n/en/docusaurus-plugin-content-docs/current/media-insights/italian.md
          rm -f i18n/en/docusaurus-plugin-content-docs/current/media-insights/hungarian.md
          rm -f i18n/en/docusaurus-plugin-content-docs/current/media-insights/german.md
          rm -f i18n/en/docusaurus-plugin-content-docs/current/media-insights/french.md
          rm -f i18n/en/docusaurus-plugin-content-docs/current/media-insights/english.md
          rm -f i18n/en/docusaurus-plugin-content-docs/current/media-insights/dutch.md
          rm -f i18n/en/docusaurus-plugin-content-docs/current/media-insights/czech-slovak.md

      - name: Upload sources to Crowdin
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}
        run: npx crowdin upload

      - name: Download translations from Crowdin
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}
        run: npx crowdin download

      - name: Check for translation updates
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "No translation updates"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Translation updates found"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push translation updates
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add i18n/
          git commit -m "🌐 Update translations from Crowdin

          - Sync latest translations from Crowdin
          - Auto-generated by GitHub Actions

          Co-authored-by: Crowdin <noreply@crowdin.com>" || exit 0
          git push

      - name: Build site with all locales (verification)
        run: npm run build