name: DocSearch Indexing (Disabled)

# Workflow disabled - only manual trigger available
on:
  # Manual trigger only (workflow effectively disabled)
  workflow_dispatch:

jobs:
  algolia-index:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Algolia DocSearch Scraper
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          docker run \
            --env APPLICATION_ID="$APPLICATION_ID" \
            --env API_KEY="$API_KEY" \
            --env "CONFIG=$(cat docsearch-config.json | jq -r tostring)" \
            algolia/docsearch-scraper:latest

      - name: Notify completion
        run: echo "✅ DocSearch indexing completed successfully"